name: deno
version: 
summary: Deno
description: |
  Deno

base: core24
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]

parts:
  deno:
    plugin: dump
    build-packages:
      - unzip
      - curl
    source: https://github.com/denoland/deno_install.git
    override-build: |
      export DENO_INSTALL=$SNAPCRAFT_PART_BUILD
      ./install.sh
      cp $SNAPCRAFT_PROJECT_DIR/wrapper.sh $SNAPCRAFT_PART_INSTALL/wrapper.sh
      cp $SNAPCRAFT_PART_BUILD/bin/deno $SNAPCRAFT_PART_INSTALL/deno
apps:
  deno:
    environment:
      HOME: "$SNAP_REAL_HOME"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache"
    command: wrapper.sh
    plugs:
      - network
      - network-bind
      - home
