name: deno
version: v1.20.1
summary: Deno
description: |
  Deno

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  deno:
    plugin: dump
    build-packages:
      - unzip
      - curl
    source: https://github.com/denoland/deno_install.git
    override-build: |
      export DENO_INSTALL=$SNAPCRAFT_PART_BUILD
      ./install.sh

    organize:
      $SNAPCRAFT_PART_BUILD/bin/deno: bin/deno

apps:
  deno:
    environment:
      HOME: "/home/$USER"
      XDG_CACHE_HOME: "$SNAP_USER_DATA/.cache"
    command: bin/deno
    plugs:
      - network
      - network-bind
      - home
