name: deno
version: 1.0.0
summary: Deno
description: |
  Deno

base: core
grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  deno:
    plugin: dump
    build-packages:
      - unzip
    source: https://github.com/denoland/deno_install.git
    override-build: |
      export DENO_INSTALL=$SNAPCRAFT_PART_BUILD
      ./install.sh

    organize:
      $SNAPCRAFT_PART_BUILD/bin/deno: bin/deno

apps:
  deno:
    command: bin/deno
    plugs:
      - network
      - network-bind
      - home
