name: Update release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create snapcraft.yaml
        run: ./updater.sh

      - name: Check snapcraft.yaml exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "snapcraft.yaml"

      - name: Build snap
        if: steps.check_files.outputs.files_exists == 'true'
        uses: snapcore/action-build@v1
        id: build

      - name: Release snap
        if: steps.build.outputs.snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
