name: Watch for Updates
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Update snapcraft.yaml
        id: get_version
        run: |
          rm snapcraft.yaml
          echo "version=$(./updater.sh)" >> "$GITHUB_OUTPUT"

      - name: Has updated
        id: has_run
        run: echo "changes=$(git diff --name-only HEAD^1 HEAD)" >> "$GITHUB_OUTPUT"

      - name: Push change
        if: steps.has_run.outputs.changes == 'snapcraft.yaml'
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
